Task1_0610. 주어진 두 배열 arr1과 arr2에서, arr2의 요소가 10보다 큰 위치의 arr1 요소들을 선택하세요.

arr1 = np.array([10, 20, 30, 40, 50])<br>
arr2 = np.array([5, 15, 25, 10, 35])

In [1]:
import numpy as np
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([5, 15, 25, 10, 35])

In [2]:
# arr의 요소가 10보다 큰 위치인 인덱스 뽑기
idx_2=[]
for idx, value in enumerate(arr2):
    if value>10:
        idx_2.append(idx)

idx_array=np.array(idx_2)
print(idx_array)

# 해당 인덱스를 array로 만들어주고,
selected=arr1[idx_array]

# arr1 요소 중 arr2의 요소가 10보다 큰 위치에 있는 것들 설렉:
print(selected)

[1 2 4]
[20 30 50]


In [3]:
# 강사님 풀이:
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([5, 15, 25, 10, 35])
print([arr2>10])

result=arr1[arr2>10]
result

[array([False,  True,  True, False,  True])]


array([20, 30, 50])

Task2_0610. 주어진 배열에서 짝수 인덱스에 있는 요소들을 선택하세요.

arr = np.array([5, 10, 15, 20, 25, 30, 35, 40])

In [ ]:
arr = np.array([5, 10, 15, 20, 25, 30, 35, 40])
index_arr=np.array([2,4,6]) # <== 0은 짝수가 아님. 그 외 인덱스 넘버가 짝수인 케이스만
result=arr[index_arr]
print(result)

In [4]:
# 강사님 풀이
arr = np.array([5, 10, 15, 20, 25, 30, 35, 40])
arr[::2]

array([ 5, 15, 25, 35])

Task3_0610. 주어진 배열에서 20보다 작은 요소들의 값을 0으로 변경하세요.

arr = np.array([10, 25, 30, 15, 40, 5])

In [ ]:
arr = np.array([10, 25, 30, 15, 40, 5])
arr_rev=np.where(arr<20,0,arr)
print(arr_rev)

0610 numpy Quiz 20문제 풀기

In [ ]:
# << numpy_quiz1 >> 파일에서 풀었음