Task1_0611. 주어진 대각 행렬의 역행렬을 구하고, 역행렬이 맞는지 확인하세요.

D = np.diag([1, 2, 3])

In [ ]:
import numpy as np

D = np.diag([1, 2, 3])
D_inverse=np.linalg.inv(D)
D_inverse_check=np.linalg.det(D_inverse)

print("대각행렬 D\n", D,'\n')
print("D의 역행렬\n", D_inverse,'\n')
print("D의 역행렬 존재여부\n",D_inverse_check,'\n')
if D_inverse_check!=0:
    print(f"D의 역행렬이 맞음")

대각행렬 D
 [[1 0 0]
 [0 2 0]
 [0 0 3]] 

D의 역행렬
 [[1.         0.         0.        ]
 [0.         0.5        0.        ]
 [0.         0.         0.33333333]] 

D의 역행렬 존재여부
 0.16666666666666669 

D의 역행렬이 맞음


In [ ]:
# 강사님 풀이:
# 역행렬이 맞는지는 행렬의 곱을 해서 단위행렬 (주대각선이 1이고 나머지는 0) 이 나오면 됨
print(np.dot(D, D_inverse))

Task2_0611. 임의의 상삼각 행렬을 생성하고, 그 행렬로 부터 하삼각 행렬을 구하여 출력하세요.

In [ ]:
a=np.array([[1,2,3],[4,5,6],[1,3,6]])
a_triu=np.triu(a)
a_tril=np.tril(a_triu)

# print("원래 행렬: \n",a,'\n')
print("상삼각 행렬: \n", a_triu,'\n')
print("위 상삼각 행렬의 하삼각 행렬: \n", a_tril,'\n')

상삼각 행렬: 
 [[1 2 3]
 [0 5 6]
 [0 0 6]] 

위 상삼각 행렬의 하삼각 행렬: 
 [[1 0 0]
 [0 5 0]
 [0 0 6]] 



In [ ]:
# 강사님 풀이:
# 상삼각 행렬에서 하삼각 행렬을 구하려면 상삼각 행렬을 전치하면 됨
a_tril=a_triu.T
print('상삼각행렬:\n', a_triu,'\n')
print('하삼각행렬:\n',a_tril)

상삼각행렬:
 [[1 2 3]
 [0 5 6]
 [0 0 6]] 

하삼각행렬:
 [[1 0 0]
 [2 5 0]
 [3 6 6]]


Task3_0611. 주어진 행렬의 역행렬을 구하고, 역행렬이 맞는지 확인하세요.

A = np.array([[4, 7], [2, 6]])

In [ ]:
A = np.array([[4, 7], [2, 6]])
A_inverse=np.linalg.inv(A)
A_inverse_check=np.linalg.det(A_inverse)

print("원래 행렬: \n", A, '\n')
print("역행렬: \n", A_inverse, '\n')
print("역행렬 여부 확인: \n", A_inverse_check)

if A_inverse_check!=0:
    print("\n역행렬이 맞음")

원래 행렬: 
 [[4 7]
 [2 6]] 

역행렬: 
 [[ 0.6 -0.7]
 [-0.2  0.4]] 

역행렬 여부 확인: 
 0.10000000000000002

역행렬이 맞음


In [ ]:
# 강사님 풀이:
# 역행렬이 맞는지는 행렬의 곱을 해서 단위행렬 (주대각선이 1이고 나머지는 0) 이 나오면 됨
# 혹은 np.allclose(행렬@역행렬, 단위행렬) 했을 때 True가 나오거나

A = np.array([[4, 7], [2, 6]])

A_inv=np.linalg.inv(A) # 역행렬
result=np.dot(A,A_inv) # 행렬과 역행렬의 곱
l=np.eye(2) # 단위행렬
np.allclose(result,l) # 역행렬이 맞는지 확인

True

Task4_0611. 주어진 데이터 포인트와 모델 파라미터를 사용하여 선형 회귀 모델의 예측값을 계산하세요.

X = np.array([1, 2, 3])

- 1단계 : 주어진 입력 데이터 포인트 X와 모델 파라미터 θ를 정의.
- 2단계 : 행렬 곱을 사용하여 예측값 y를 계산.

In [ ]:
# 주어진 벡터:
X = np.array([1, 2, 3])
print("주어진 벡터:\n", X,'\n')

# 모델 파라미터:
W=np.random.randint(-5,5,size=3).reshape(3,1)
print("모델 파라미터:\n",W)

# 선형 회귀모델 예측값 계산:
y=np.dot(X,W)
print("\n예측값:\n",y)

주어진 벡터:
 [1 2 3] 

모델 파라미터:
 [[ 3]
 [-1]
 [ 0]]

예측값:
 [1]


In [ ]:
# 강사님 풀이:
# 입력 데이터 포인트 (1,x1,x2)
X = np.array([1, 2, 3])

# 모델 파라미터 (bias, w1, w2)
theta=np.array([0.5,1.5,-2])

# 선형 회귀 모델의 예측값 계산
y_pred=np.dot(X, theta)

print("Input Data Point X=",X)
print("Model Parameters theta=",theta)
print("Predicted Value y=",y_pred)

Input Data Point X= [1 2 3]
Model Parameters theta= [ 0.5  1.5 -2. ]
Predicted Value y= -2.5


Task5_0611. 주어진 입력 벡터와 가중치 행렬을 사용하여 신경망의 단일 계층 출력을 계산하세요.

- 1단계: 입력 벡터 X와 가중치 행렬 W를 정의.
- 2단계: 행렬 곱을 사용하여 계층의 출력을 계산.

In [ ]:
X = np.array([0.5, 1.0, -1.5])

# 1단계: 입력 벡터 X와 가중치 행렬 W를 정의.
np.random.seed(0)
W=np.random.randint(-5,10,size=9).reshape(3,3)

print("입력 벡터 X: \n", X,'\n')
print("가중치 행렬 X: '\n", W, '\n')

# 2단계: 행렬 곱을 사용하여 계층의 출력을 계산.
result=np.dot(X,W)
print("신경망의 단일 계층: \n", result)

입력 벡터 X: 
 [ 0.5  1.  -1.5] 

가중치 행렬 X: '
 [[ 7  0 -5]
 [-2  6 -2]
 [ 2  4 -2]] 

신경망의 단일 계층: 
 [-1.5  0.  -1.5]


Task6_0611. 주어진 입력 벡터에 대해 신경망의 활성화 함수(ReLU, 시그모이드)를 적용하여 출력을 계산하세요.

X = np.array([1, -2, 3])

- 1단계: 입력 벡터 X를 정의.
- 2단계: 가중치 행렬 W와 편향 벡터 b를 정의.
- 3단계: 활성화 함수(ReLU, 시그모이드)를 적용하여 출력을 계산
활성화 함수 적용<br>
output_relu = relu(Z)<br>
output_sigmoid = sigmoid(Z)

In [2]:
# 1단계: 입력 벡터 X를 정의.
import numpy as np
X = np.array([1, -2, 3])

# 2단계: 가중치 행렬 W와 편향 벡터 b를 정의. ==> 행렬과 벡터 하나 만들라는 말
# 가중치 행렬 :
W=np.random.randint(-10,10,size=9).reshape(3,3)

# 편향 벡터 b :
b=np.random.randint(-50,50,size=3)

print("입력 벡터 X:\n", X, '\n')
print("가중치 행렬 W:\n", W, '\n')
print("편향 벡터 b:\n", b, '\n')

# 3단계: 주어진 두 함수 중 하나를 쓰면 됨 (relu 사용 예정)
# relu(z) 정의
def relu(Z):
    return np.maximum(0,Z)

# 신경망 일반적인 공식: Z=WX+b
Z=np.dot(X,W)+b
print("선형 변환 Z:\n",Z,'\n')

# relu(z) 적용:
output_relu = relu(Z)

print("활성화 함수 relu를 적용:\n",output_relu)

입력 벡터 X:
 [ 1 -2  3] 

가중치 행렬 W:
 [[ 3 -6 -3]
 [-5  9 -4]
 [ 7  3  5]] 

편향 벡터 b:
 [ 10 -41 -27] 

선형 변환 Z:
 [ 44 -56  -7] 

활성화 함수 relu를 적용:
 [44  0  0]


In [ ]:
# 강사님 풀이:

# 활성화 함수 정의
def relu(x):
    return np.maximum(0,x) # 음수면 0으로, 양수면 자기자신으로

def sigmoid(x):
    return 1/(1+np.exp(-x)) # 0.5이상이며 1로, 그보다 작다면 음수 방향으로

# 입력 벡터 정의
X=np.array([1,-2,3])

# 가중치 행렬과 편향 벡터 정의
W=np.array([[0.2,-0.5,0.3],
            [0.4,0.1,-0.2],
            [-0.3,0.4,0.6]])
b=np.array([0.1,-0.2,0.3])

# 신경망의 선형 변환 계산
Z=np.dot(W,X)+b

# 활성화 함수 적용
output_relu = relu(Z)
output_sigmoid = sigmoid(Z)

print("Input Vector X=",X)
print("Weight Matrix W=\n",W)
print("Bias Vector b=\n",b)
print("Linear Transformation Z=",Z)
print("Output after ReLu Activation=\n",output_relu)
print("Output after Sigmoid Activation=\n",output_sigmoid)

Input Vector X= [ 1 -2  3]
Weight Matrix W=
 [[ 0.2 -0.5  0.3]
 [ 0.4  0.1 -0.2]
 [-0.3  0.4  0.6]]
Bias Vector b=
 [ 0.1 -0.2  0.3]
Linear Transformation Z= [ 2.2 -0.6  1. ]
Output after ReLu Activation=
 [2.2 0.  1. ]
Output after Sigmoid Activation=
 [0.90024951 0.35434369 0.73105858]


Task7_0611. 주어진 선형 방정식을 행렬 형태로 나타내고, 역행렬을 사용하여
x와 y를 구하세요.

$\begin{cases}
3x + 4y = 10 \\
2x + y = 5
\end{cases}$

단계:
1. 계수 행렬 A와 결과 벡터 b를 정의.
2. 행렬 A의 역행렬을 구한다.
3. 역행렬을 사용하여 변수 x를 구한다.

In [ ]:
# 1. 계수 행렬 A와 결과 벡터 b를 정의.
A=np.array([[3,4],[2,1]])
b=np.array([[10],[5]])

print("행렬 A:\n",A,'\n')
print("벡터 b:\n",b,'\n')

# 2. 행렬 A의 역행렬을 구한다.
A_inverse=np.linalg.inv(A)
print("행렬 A의 역행렬:\n",A_inverse,'\n')

# 3. 역행렬을 사용하여 변수 x를 구한다.
print("역행렬A @ 벡터 b:\n",np.dot(A_inverse,b))
print("\n따라서, x=2")

행렬 A:
 [[3 4]
 [2 1]] 

벡터 b:
 [[10]
 [ 5]] 

행렬 A의 역행렬:
 [[-0.2  0.8]
 [ 0.4 -0.6]] 

역행렬A @ 벡터 b:
 [[2.]
 [1.]]

따라서, x=2


[풀이]
주어진 선형방정식을 행렬 형태로 나타내면 다음과 같다: \\
$A\mathbf{x} = \mathbf{b}$ \\
여기서 \\
$A = \begin{bmatrix}3 & 4 \\2 & 1\end{bmatrix}$,

$\mathbf{x} = \begin{bmatrix}x \\y\end{bmatrix}$,

$\mathbf{b} = \begin{bmatrix}10 \\5\end{bmatrix}$

$\mathbf{x} = A^{-1} \mathbf{b}$

In [ ]:
# 강사님 풀이:
# 주어진 선형 방정식을 행렬 형태로 나타나면 다음과 같음 : Ax=b
# 따라서, x를 구하려면 다음의 방식으로 계산해야함 : x=A역행렬b

A=np.array([[3,4],[2,1]])
b=np.array([[10],[5]])

# 역행렬 계산
A_inv=np.linalg.inv(A)

# 해 계산
x=np.dot(A_inv, b)

print("Coefficient Matrix A='\n",A)
print("Result Vector b=\n",b)
print("Inverse of A (A_inv)=\n",A_inv)
print("Solution Vector x=\n",x)


Coefficient Matrix A='
 [[3 4]
 [2 1]]
Result Vector b=
 [[10]
 [ 5]]
Inverse of A (A_inv)=
 [[-0.2  0.8]
 [ 0.4 -0.6]]
Solution Vector x=
 [[2.]
 [1.]]


Task8_0611. 주어진 2D 평면의 점을 특정 변환 행렬을 사용하여 변환한 후, 변환된 좌표를 원래 좌표로 되돌리세요.

원래 점의 좌표 p와 변환 행렬 T 정의<br>
p = np.array([1, 2])<br>
T = np.array([[2, 0], [0, 3]])

단계
1. 원래 점의 좌표 p와 변환 행렬 T를 정의.
2. 변환 행렬 T를 사용하여 새로운 좌표 p를 계산.
3. 변환 행렬 T의 역행렬을 사용하여 새로운 좌표 p에서 원래 좌표 p를 복원.

In [3]:
p = np.array([1, 2]) # 원래 점의 좌표
T = np.array([[2, 0], [0, 3]]) # 변환 행렬 T

# 1. 원래 점의 좌표 p와 변환 행렬 T를 정의.
print("원래 점의 좌표:\n", p,'\n')
print("점 위치를 옮길 변환 행렬 T:\n", T,'\n')

# 2. 변환 행렬 T를 사용하여 새로운 좌표 p'를 계산.
p_relocated=np.dot(p,T)
print("p의 새로운 좌표:\n", p_relocated,'\n')

# 3. 변환 행렬 T의 역행렬을 사용하여 새로운 좌표 p'에서 원래 좌표 p를 복원.
p_restored=np.dot(p_relocated,np.linalg.inv(T))
print("p의 좌표 복원:\n", p_restored,'\n')


원래 점의 좌표:
 [1 2] 

점 위치를 옮길 변환 행렬 T:
 [[2 0]
 [0 3]] 

p의 새로운 좌표:
 [2 6] 

p의 좌표 복원:
 [1. 2.] 



In [4]:
# 강사님 풀이:
p = np.array([1, 2]) # 원래 점의 좌표
T = np.array([[2, 0], [0, 3]]) # 변환 행렬 T

# 새로운 좌표 p' 계산
p_prime=np.dot(p,T)

# 변환 행렬 T의 역행렬 계산
T_inv=np.linalg.inv(T)

# 원래 좌표 p 복원
p_restored=np.dot(T_inv,p_prime)

print("Original Point p=\n",p)
print("Transformation Matrix T=\n",T)
print("Transofrmed Point p'=\n", p_prime)
print("Inverse of T (T_inv)=\n",T_inv)
print("Restored Point p=\n",p_restored)

Original Point p=
 [1 2]
Transformation Matrix T=
 [[2 0]
 [0 3]]
Transofrmed Point p'=
 [2 6]
Inverse of T (T_inv)=
 [[0.5        0.        ]
 [0.         0.33333333]]
Restored Point p=
 [1. 2.]
